/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFunctionNode,
  IFunctionNodeInterface,
} from "../../../contracts/Interfaces.sol/IFunctionNode";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IBehaviorGraph",
        name: "behaviorGraph",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "_nodeId",
        type: "uint16",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFunctionNode__factory {
  static readonly abi = _abi;
  static createInterface(): IFunctionNodeInterface {
    return new utils.Interface(_abi) as IFunctionNodeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFunctionNode {
    return new Contract(address, _abi, signerOrProvider) as IFunctionNode;
  }
}
