/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  NodeState,
  NodeStateInterface,
} from "../../../contracts/NodeState.sol/NodeState";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea264697066735822122078249dfbbb212eee00e5912d43a58ba9eaf304457b2e4d3c71a9b833c075562864736f6c63430008090033";

type NodeStateConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NodeStateConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NodeState__factory extends ContractFactory {
  constructor(...args: NodeStateConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<NodeState> {
    return super.deploy(overrides || {}) as Promise<NodeState>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): NodeState {
    return super.attach(address) as NodeState;
  }
  override connect(signer: Signer): NodeState__factory {
    return super.connect(signer) as NodeState__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NodeStateInterface {
    return new utils.Interface(_abi) as NodeStateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NodeState {
    return new Contract(address, _abi, signerOrProvider) as NodeState;
  }
}
